#pragma once

#include "CoreMinimal.h"
#include "ArenaTypes.h"

class UMaterialInstanceDynamic;
class UMaterialInterface;
class UMeshComponent;
class UStaticMesh;
class UStaticMeshComponent;
class UWorld;

/** Tileable level textures, generated by Tools/generate_textures.py. */
enum class EArenaSurface : uint8
{
	Tiles,
	Panels,
	Plate,
	Concrete,
	Bricks,
	Sand,
};

/** How a level block looks: one texture on its top faces, another on its sides, tinted. */
struct FArenaSurfaceStyle
{
	EArenaSurface Top;
	EArenaSurface Side;
	FLinearColor Tint;
};

/**
 * Shared meshes and materials. Art lives in /Game/Art (generated by the scripts in
 * Tools/, see the README); beams and blasts use the engine's basic shapes.
 */
namespace ArenaVisuals
{
	ARENA_API UStaticMesh* Cube();     // 100 cm, pivot at center
	ARENA_API UStaticMesh* Sphere();   // 100 cm diameter
	ARENA_API UStaticMesh* Cylinder(); // 100 cm diameter, 100 cm tall, Z-up

	/** /Game/Art/Meshes/<Name>. */
	ARENA_API UStaticMesh* ArtMesh(const TCHAR* Name);

	/** Gun model, with its origin at the right hand's grip and "Muzzle" / "LeftHand" / "Spin" sockets. */
	ARENA_API UStaticMesh* WeaponMesh(EArenaWeapon Weapon);

	/** The weapon's spinning part (barrels, blade, coil), attached at the "Spin" socket, or null. */
	ARENA_API UStaticMesh* WeaponSpinMesh(EArenaWeapon Weapon);

	/** Sets up a purely visual mesh: no collision, no navigation. */
	ARENA_API void SetupCosmeticMesh(UStaticMeshComponent* Comp, UStaticMesh* Mesh);

	/** Colours a model's "Accent" (paint) and "Glow" (emissive) material slots. */
	ARENA_API void SetPropColors(UMeshComponent* Comp, const FLinearColor& Accent, const FLinearColor& Glow);

	/** Sets a scalar ("Emissive", "Pulse") on the material of a model's Glow slot. */
	ARENA_API void SetGlowParam(UMeshComponent* Comp, FName Param, float Value);

	/** Puts the unlit additive effect material on every slot. Returns it for fading ("Opacity"). */
	ARENA_API UMaterialInstanceDynamic* SetFX(UMeshComponent* Comp, const FLinearColor& Color, float Intensity, float FresnelExp = 0.f);

	/** The level material for a surface style, shared by every block using it. */
	ARENA_API UMaterialInterface* SurfaceMaterial(const FArenaSurfaceStyle& Style);

	/** Spawns a short-lived beam (rail trail / tracer) on this machine only. */
	ARENA_API void SpawnBeam(UWorld* World, const FVector& Start, const FVector& End, const FLinearColor& Color, float Width, float Life);

	/** Spawns a short-lived expanding glow on this machine only; big ones also light up the area. */
	ARENA_API void SpawnBlast(UWorld* World, const FVector& Location, const FLinearColor& Color, float Radius, float Life);
}
